"""RunPod Serverless worker: one image, both GPU jobs.

Why one image rather than two endpoints. Building an avatar needs LivePortrait
(photograph to a base clip with real head motion) and CosyVoice (the person's
own voice from a short reference). Splitting them doubles the cold starts and
doubles the number of endpoints whose safety settings have to stay correct,
for no isolation benefit - the two never run concurrently and neither is
latency-critical, because this is signup-time batch work rather than call-time.

Why a handler rather than the FastAPI servers in infra/liveportrait and
infra/cosyvoice. Those images expose HTTP and expect something to keep them
alive, which is the Pod shape this project deliberately moved away from. Here
the platform starts a worker only when a job is queued and stops it when the
job ends, so the process has no lifecycle of its own to get wrong.

Models are loaded lazily and cached in module scope. RunPod reuses a warm
worker for consecutive jobs, so the second job in a burst skips the load; a
cold worker pays it once. Loading at import instead would make a worker that
cannot reach its weights crash-loop rather than return a usable error.
"""

from __future__ import annotations

import base64
import binascii
import os
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from pathlib import Path
from threading import Lock

import runpod

sys.path.insert(0, "/opt/LivePortrait")

LP_ROOT = Path("/opt/LivePortrait")
LP_WEIGHTS = Path(os.environ.get("LP_WEIGHTS", "/opt/LivePortrait/pretrained_weights"))
COSY_MODEL_DIR = Path(os.environ.get("COSY_MODEL_DIR", "/models/CosyVoice2-0.5B"))

# Long edge the source photograph is reduced to before inference. LivePortrait
# crops the face to 512 regardless, but composites back at source resolution,
# so a 5MP phone photograph spends minutes pasting detail that is discarded.
MAX_SOURCE_EDGE = 1024

# What CosyVoice expects a prompt recording to be sampled at.
PROMPT_RATE = 16000

# Ceiling on anything returned inline as base64. RunPod delivers job output as
# JSON through /status, and a large payload there is slow and fragile. Above
# this the job fails with an explicit message rather than silently truncating,
# which is the point at which object storage has to be configured.
MAX_INLINE_BYTES = 6 * 1024 * 1024

# Below the platform's executionTimeout so a stuck subprocess is killed here,
# with a readable error, before the platform kills the whole worker.
ANIMATE_TIMEOUT_S = 720

LP_REQUIRED_WEIGHTS = (
    "liveportrait/base_models/appearance_feature_extractor.pth",
    "liveportrait/base_models/motion_extractor.pth",
    "liveportrait/base_models/spade_generator.pth",
    "liveportrait/base_models/warping_module.pth",
    "liveportrait/landmark.onnx",
    "liveportrait/retargeting_models/stitching_retargeting_module.pth",
)


class TaskError(RuntimeError):
    """A failure that should be reported to the caller, not retried."""


# --------------------------------------------------------------------------
# payload helpers


def _decode(field: str, value: object) -> bytes:
    if not isinstance(value, str) or not value:
        raise TaskError(f"{field} must be a non-empty base64 string")
    try:
        return base64.b64decode(value, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise TaskError(f"{field} is not valid base64: {exc}") from exc


def _encode(field: str, data: bytes) -> str:
    if len(data) > MAX_INLINE_BYTES:
        raise TaskError(
            f"{field} is {len(data) // 1024}KB, over the "
            f"{MAX_INLINE_BYTES // 1024}KB inline limit; configure object storage"
        )
    return base64.b64encode(data).decode("ascii")


def _limit_resolution(path: Path, max_edge: int) -> None:
    import cv2

    image = cv2.imread(str(path))
    if image is None:
        raise TaskError("source image could not be decoded")
    height, width = image.shape[:2]
    if max(height, width) <= max_edge:
        return
    scale = max_edge / max(height, width)
    resized = cv2.resize(
        image, (round(width * scale), round(height * scale)), interpolation=cv2.INTER_AREA
    )
    cv2.imwrite(str(path), resized, [cv2.IMWRITE_JPEG_QUALITY, 95])


# --------------------------------------------------------------------------
# LivePortrait


def _animate(payload: dict) -> dict:
    """Photograph plus a motion template in, a base clip out.

    The motion template is supplied per request rather than baked into the
    image. It is generated by src/avatar/ingest/idle_motion.py, and which style
    is used is a per-avatar decision - an extracted clip from a real person
    would make every avatar move like the same stranger.
    """
    missing = [name for name in LP_REQUIRED_WEIGHTS if not (LP_WEIGHTS / name).exists()]
    if missing:
        raise TaskError(f"LivePortrait weights missing from the image: {missing}")

    workdir = Path(tempfile.mkdtemp(prefix="animate-", dir="/tmp"))
    source = workdir / "source.jpg"
    source.write_bytes(_decode("image", payload.get("image")))
    _limit_resolution(source, MAX_SOURCE_EDGE)

    driving = workdir / "driving.pkl"
    driving.write_bytes(_decode("motion_template", payload.get("motion_template")))

    command = [
        sys.executable, "inference.py",
        "-s", str(source),
        "-d", str(driving),
        "-o", str(workdir),
    ]

    started = time.perf_counter()
    try:
        result = subprocess.run(
            command,
            cwd=str(LP_ROOT),
            capture_output=True,
            text=True,
            timeout=ANIMATE_TIMEOUT_S,
            # The return code is inspected below so the model's own stderr can
            # be returned to the caller; raising here would discard it.
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise TaskError(f"animation exceeded {ANIMATE_TIMEOUT_S}s") from exc

    if result.returncode != 0:
        raise TaskError(f"animation failed: {(result.stderr or result.stdout)[-800:]}")

    # Selected by name, not by size. LivePortrait writes both the animation and
    # a side-by-side comparison; the comparison holds two frames per frame and
    # is usually the larger file, so picking the biggest returns the wrong one.
    produced = [p for p in sorted(workdir.rglob("*.mp4")) if "concat" not in p.name]
    if not produced:
        raise TaskError("animation produced no video")

    clip = produced[0]
    return {
        "video": _encode("video", clip.read_bytes()),
        "video_format": "mp4",
        "seconds": round(time.perf_counter() - started, 2),
    }


# --------------------------------------------------------------------------
# CosyVoice

_cosy = None
_cosy_lock = Lock()


def _cosy_model():
    global _cosy
    with _cosy_lock:
        if _cosy is None:
            if not COSY_MODEL_DIR.exists():
                raise TaskError(f"CosyVoice weights missing at {COSY_MODEL_DIR}")
            from cosyvoice.cli.cosyvoice import CosyVoice2

            _cosy = CosyVoice2(
                str(COSY_MODEL_DIR), load_jit=False, load_trt=False, fp16=False
            )
        return _cosy


def _load_prompt(path: Path):
    """The reference recording as a (1, N) float tensor at PROMPT_RATE.

    Read with soundfile rather than CosyVoice's own load_wav, which goes
    through torchaudio and now delegates decoding to TorchCodec - a package
    that fails at call time rather than at import when it has no wheel.
    """
    import librosa
    import numpy as np
    import soundfile as sf
    import torch

    audio, rate = sf.read(str(path), dtype="float32")
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    if rate != PROMPT_RATE:
        audio = librosa.resample(audio, orig_sr=rate, target_sr=PROMPT_RATE)
    return torch.from_numpy(np.ascontiguousarray(audio)).unsqueeze(0)


def _speak(payload: dict) -> dict:
    """Text plus a reference recording in, that person's voice out."""
    import io

    import soundfile as sf
    import torch

    text = payload.get("text")
    if not isinstance(text, str) or not text.strip():
        raise TaskError("text must be a non-empty string")

    workdir = Path(tempfile.mkdtemp(prefix="speak-", dir="/tmp"))
    reference = workdir / "reference.wav"
    reference.write_bytes(_decode("reference", payload.get("reference")))

    model = _cosy_model()
    prompt = _load_prompt(reference)
    started = time.perf_counter()

    chunks = [
        out["tts_speech"]
        for out in model.inference_zero_shot(
            text, payload.get("reference_text", ""), prompt, stream=False
        )
    ]
    if not chunks:
        raise TaskError("synthesis produced no audio")

    buffer = io.BytesIO()
    sf.write(
        buffer, torch.cat(chunks, dim=1).squeeze(0).numpy(), model.sample_rate, format="WAV"
    )
    return {
        "audio": _encode("audio", buffer.getvalue()),
        "audio_format": "wav",
        "sample_rate": model.sample_rate,
        "seconds": round(time.perf_counter() - started, 2),
    }


# --------------------------------------------------------------------------
# health


def _health(_payload: dict) -> dict:
    """What this worker can actually do, without doing any of it.

    Cheap on purpose: it is the first thing to run against a new endpoint, and
    the answer should cost a few seconds of a cold start rather than a full
    model load.
    """
    import torch

    return {
        "cuda": torch.cuda.is_available(),
        "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
        "liveportrait_weights_missing": [
            name for name in LP_REQUIRED_WEIGHTS if not (LP_WEIGHTS / name).exists()
        ],
        # Recorded so any health dump shows the restricted detection models are
        # absent rather than merely unused: LivePortrait's licence requires
        # InsightFace to be replaced for commercial use, and it is.
        "insightface_present": (LP_WEIGHTS / "insightface").exists(),
        "cosyvoice_weights": COSY_MODEL_DIR.exists(),
        "cosyvoice_loaded": _cosy is not None,
    }


TASKS = {"animate": _animate, "speak": _speak, "health": _health}


def handler(job: dict) -> dict:
    """Dispatch one job.

    Returns an {"error": ...} object rather than raising for anything the
    caller got wrong, so a bad request is one failed job and not a worker that
    the platform retries. Unexpected failures are also returned rather than
    propagated: a crash here would have the same billing cost and less
    information in it.
    """
    payload = job.get("input") or {}
    name = payload.get("task", "animate")

    task = TASKS.get(name)
    if task is None:
        return {"error": f"unknown task {name!r}; expected one of {sorted(TASKS)}"}

    job_id = payload.get("job_id") or uuid.uuid4().hex[:12]
    started = time.perf_counter()
    try:
        result = task(payload)
    except TaskError as exc:
        return {"error": str(exc), "task": name, "job_id": job_id}
    except Exception as exc:  # noqa: BLE001
        return {"error": f"{type(exc).__name__}: {exc}", "task": name, "job_id": job_id}

    return {**result, "task": name, "job_id": job_id,
            "total_seconds": round(time.perf_counter() - started, 2)}


# --------------------------------------------------------------------------
# face geometry sidecar

FACE_SERVICE_URL = os.environ.get("FACE_SERVICE_URL", "http://127.0.0.1:7001")
# Its own interpreter, not this one. MediaPipe and CosyVoice disagree about
# numpy, and resolving that in a single environment means one of them runs on
# a version it was never tested against. Two virtualenvs cost disk, which is
# cheap, instead of correctness, which is not.
FACE_PYTHON = os.environ.get("FACE_PYTHON", "/opt/facegeom-venv/bin/python")
FACE_READY_TIMEOUT_S = 60

# Where the bootstrap unpacked us. The face service and the LivePortrait patch
# travel in the same private bundle as this file, so they are found relative to
# it rather than at a path baked into the image.
APP_DIR = Path(os.environ.get("APP_DIR", "/opt/app"))


def _start_face_service() -> subprocess.Popen | None:
    """Run the MediaPipe face service inside this worker.

    LivePortrait's cropper reaches it through facegeom_shim, which replaces the
    InsightFace detector that its licence forbids commercially. In the compose
    setup that service is a separate container; here it is a local process, so
    the shim and the cropper patch stay byte-identical to what is already
    tested and only the URL differs.

    It is started rather than imported because MediaPipe holds global state
    that LivePortrait's own onnxruntime session has no reason to share, and
    because a crash in the detector should fail one job rather than take the
    worker with it.

    A worker that comes up without it still starts. Jobs then fail with the
    detector's own error, which says more than a crash-looping worker does.
    """
    process = subprocess.Popen(
        [FACE_PYTHON, "-m", "uvicorn", "server:app",
         "--host", "127.0.0.1", "--port", "7001", "--log-level", "warning"],
        cwd="/opt/facegeom",
    )

    import urllib.error
    import urllib.request

    deadline = time.monotonic() + FACE_READY_TIMEOUT_S
    while time.monotonic() < deadline:
        if process.poll() is not None:
            print(f"face service exited with {process.returncode}", flush=True)
            return None
        try:
            with urllib.request.urlopen(f"{FACE_SERVICE_URL}/health", timeout=2):
                print("face service ready", flush=True)
                return process
        except (urllib.error.URLError, OSError):
            time.sleep(0.5)

    print(f"face service not ready after {FACE_READY_TIMEOUT_S}s", flush=True)
    return process


def _patch_cropper() -> None:
    """Replace LivePortrait's InsightFace detector with ours.

    Applied here rather than at image build time because the shim is ours and
    the image is public. It runs once per cold worker and fails the start
    rather than the first job: a cropper still calling InsightFace would look
    like it worked and would breach the licence quietly.
    """
    shim = APP_DIR / "liveportrait" / "facegeom_shim.py"
    patcher = APP_DIR / "liveportrait" / "patch_cropper.py"
    target = LP_ROOT / "src" / "utils" / "cropper.py"

    if "facegeom_shim" in target.read_text():
        return

    shutil.copyfile(shim, LP_ROOT / "src" / "utils" / "facegeom_shim.py")
    result = subprocess.run(
        [sys.executable, str(patcher)], cwd=str(LP_ROOT),
        capture_output=True, text=True, timeout=60, check=False,
    )
    if result.returncode != 0 or "facegeom_shim" not in target.read_text():
        raise SystemExit(f"could not replace the face detector: {result.stderr[-400:]}")
    print("cropper patched to use facegeom", flush=True)


if __name__ == "__main__":
    _patch_cropper()
    _start_face_service()
    runpod.serverless.start({"handler": handler})
